"""
提示词模块
"""

from .prompts import (
    CHARACTER_EXTRACTION_PROMPT,
    CHARACTER_CONFIRMATION_PROMPT,
    CHARACTER_MERGE_PROMPT,
    CHARACTER_ANALYSIS_PROMPT,
    CHARACTER_INFO_MERGE_PROMPT
)

__all__ = [
    "CHARACTER_EXTRACTION_PROMPT",
    "CHARACTER_CONFIRMATION_PROMPT",
    "CHARACTER_MERGE_PROMPT",
    "CHARACTER_ANALYSIS_PROMPT",
    "CHARACTER_INFO_MERGE_PROMPT"
]